include $(TOPDIR)/rules.mk

LUCI_TITLE:=Network Latency Test Tool
LUCI_DEPENDS:=+luci-base +fping
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
